name: Harden Runner Check
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  block-endpoints:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: block
      - name: curl random
        run: curl https://kyverno.io/
