name: Harden Runner Test
run-name: testing out harden-runner
on: [push]
jobs:
  allow-google:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: block
          allowed-endpoints: |
            google.com:443
      - name: curl google
        run: curl https://google.com
  deny-google:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: block
      - name: curl google
        run: curl https://google.com
