name: Harden Runner Check
run-name: testing out harden-runner check
on: [push]
jobs:
  block-endpoints:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
      - name: curl telebugs
        run: curl https://telebugs.com/
